Fyle report approval
fylein/fyle-slack-app pull request #16
Opened 2021-03-11 07:55 UTC by shreyanshss7

2021-03-12 11:49 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +# Generated by Django 3.1.6 on 2021-03-05 11:02
Auto generated django migration for new `report_polling_details` table

2021-03-12 11:49 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0003_user_fyle_employee_id.py
> +# Generated by Django 3.1.6 on 2021-03-11 05:47
Auto generated django migration for `fyle_employee_id` in `users` table

2021-03-15 10:19 UTC, shreyanshss7 commented on fyle_slack_app/fyle/authorization/views.py
> -    def create_user(self, slack_client, slack_team, user_id, slack_user_dm_channel_id, fyle_refresh_token):
Will need tp refactor this function since this takes in `slack_client` which doesn't define the purpose of function.
Will refactor after this PR is approved.

2021-03-18 03:47 UTC, abhishek1234321 requested changes

2021-03-18 03:47 UTC, abhishek1234321 commented on .github/workflows/github-pipeline.yaml
> +      FYLE_PLATFORM_URL: fakefyleplatformurl
do we follow [pep 8 guidelines](https://www.python.org/dev/peps/pep-0008/) or django guidelines?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
can we not have these as the top level and then import? like we do in fyle-platform-api?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
can you remove all unused imports from all files?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +            return None
if we aren't propagating the error, shouldn't we at least log it?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        if approver_reports['count'] > 0:
if `count` key isn't present then we will get a `KeyError` so I presume it will always be present? please make sure this is verified in every object where we use the object's key?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fyle_slack_app.user')),
why use this as the primary key? we could have a different column for primary key and make this as unique no?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> -    def create_user(self, slack_client, slack_team, user_id, slack_user_dm_channel_id, fyle_refresh_token):
can you put a TODO in the code till then? so that we don't miss it out?

2021-03-18 03:47 UTC, abhishek1234321 commented on requirements.txt
> +future==0.18.2
is this needed because of some python 2 library stuff?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +    report_url = '{}/{}?org_id={}'.format(report_url, report['id'], report['org_id'])
why build query params in this way? why not do like `fyle_slack_app/fyle/utils.py` line no `33`?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +    return [
put the json in a variable and then return it here? readability is important

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('updated_at', models.DateTimeField(auto_now=True)),
what about `index` on this? also shouldn't `created_at` `updated_at` have not `null` constraints?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
@aditya999123 mentioned this could be removed from the middleware in django instead of doing this for every method

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                employee_display_name = slack_utils.get_report_employee_display_name(slack_client, report['employee'])
should we put some caching for this or put this in DB? if this would be short-lived, then no need to bother

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> +    # pylint: disable=line-too-long
why are we doing this?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +            'limit': 10, # Assuming no more than 10 reports will be there in 10 min poll
what if there are more than 10? then what happens?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        submitted_at = report_polling_detail.last_successful_poll_at.isoformat()
didn't understand this, is this `rp_submitted_at`?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +                    'text': '*Submitted On:* {}'.format(readable_submitted_at)
shouldn't these be stored as variable before the json and then used here? the idea is you could console log the var value if you need to debug, here you will have to console log the entire json

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +            'report_review_in_fyle': self.review_report_in_fyle
`report_review_in_fyle` and `review_report_in_fyle` is odd no?

2021-03-18 03:47 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +    readable_submitted_at = submitted_at.strftime('%B %d, %Y')
shouldn't formatting of time be a util method?

2021-03-18 06:35 UTC, shreyanshss7 commented on requirements.txt
> +future==0.18.2
Yes this library is for compatibility b/w python2 and python 3.
This might've been added automatically as a dependent library by another library that is required by us.

2021-03-18 06:36 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +            'report_review_in_fyle': self.review_report_in_fyle
Yes my bad here

2021-03-18 06:39 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('updated_at', models.DateTimeField(auto_now=True)),
`auto_now_add=True` for `created_at` will update the entry value for `created_at` automatically when a row is being inserted.
Similarly `auto_now=True` for `updated_at` will update the `updated_at` value automatically when that row is updated.

So these operations happen at DB layer automatically.

2021-03-18 06:40 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('updated_at', models.DateTimeField(auto_now=True)),
And I'll create an index on `last_successful_poll_at` since that is value we're querying on

2021-03-18 06:42 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fyle_slack_app.user')),
This will always be unique since it's a foreign key to `user` table, didn't see any harm in keep it a primary key.

2021-03-18 06:46 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
Yes it can be removed directly from middleware. 
But a middleware is run for every request and response flow.
Removing it directly might cause unknown issues.

So, having a decorator to exempt it was the safest way here.

If we want to remove it we'll need to check thoroughly what that middleware does. But I won't recommend it for now since this exemption is used only once here.

2021-03-18 06:47 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                employee_display_name = slack_utils.get_report_employee_display_name(slack_client, report['employee'])
Yes this is short-lived + it returns two different values depending on if the user is present in slack it will return slack mention else it will return the full name of user.

2021-03-18 06:48 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        if approver_reports['count'] > 0:
Yes count key will always be present

2021-03-18 06:51 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        submitted_at = report_polling_detail.last_successful_poll_at.isoformat()
Yes it's report `submitted_at` column

2021-03-18 06:55 UTC, shreyanshss7 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
Already removed all the unused imports since this was pushed after resoling linting errors.

2021-03-18 06:56 UTC, shreyanshss7 commented on .github/workflows/github-pipeline.yaml
> +      FYLE_PLATFORM_URL: fakefyleplatformurl
We follow pep 8 guidelines

2021-03-18 06:57 UTC, shreyanshss7 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
`can we not have these as the top level and then import? like we do in fyle-platform-api?`

Pylint doesn't allow our codebase imports to be before other external library imports.

2021-03-18 06:59 UTC, shreyanshss7 commented on fyle_slack_app/fyle/authorization/views.py
> +    # pylint: disable=line-too-long
Since this linting error was being given on a function definition so I disabled it for now, since I'll be refactoring this function later.

2021-03-18 07:01 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +            'limit': 10, # Assuming no more than 10 reports will be there in 10 min poll
We won't show the > 10 report 😓  We'll need to set an unreasonable limit of reportd that won't be coming in polls so that we're on the safe side.

2021-03-18 08:04 UTC, shreyanshss7 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +    report_url = '{}/{}?org_id={}'.format(report_url, report['id'], report['org_id'])
Hey this is just a report redirect url to webapp. Don't follow `fyle_slack_app/fyle/utils.py line no 33` wrt to this.

2021-03-18 08:50 UTC, abhishek1234321 requested changes

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
what does fyle-platform-api do? did we check?

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +            'limit': 50, # Assuming no more than 50 reports will be there in 10 min poll
lol, this should do for now

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
can you check if we can do this without breaking things? read up about it?

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
point here is if we have to do this everywhere, I would rather fix it now than later

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +        token_url='{}/oauth/token'.format(settings.FYLE_ACCOUNTS_URL),
why compute this in every single method `settings.FYLE_ACCOUNTS_URL`? do you wanna compute it outside and reuse?

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fyle_slack_app.user')),
let us go with having a different primary key? tmrw if we have to make some modifications to this column cause of any reason, it will be a problem no? I understand this is short-lived, but it is better to take these calls right now than later

also we should be adding `not null` constraints no? even if it is a reference or is that not needed?

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('updated_at', models.DateTimeField(auto_now=True)),
so `not null` is not needed?

2021-03-18 08:50 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +    report_url = '{}/{}?org_id={}'.format(report_url, report['id'], report['org_id'])
ah got it

2021-03-18 09:31 UTC, shreyanshss7 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
fyle-platform-api does the same
Ex: Vendors api file
- external library import
- Internal codebase import
`import re
from typing import List

from flask import Blueprint
from flask_sqlalchemy import Model
from sqlalchemy import func, desc, or_
from sqlalchemy.sql.elements import BinaryExpression

from core.sqlalchemy.sqlalchemy_filter import FyleSQLParam
from core.schema.vendors import VendorsSchema
from core.models.vendors import Vendor
from core.libs import log, assertions

from api.flask.view import BaseView`

2021-03-18 09:33 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
Okay will check about this 👍🏽

2021-03-18 09:38 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fyle_slack_app.user')),
Yes I guess. Let me do one thing I'll make squash migrations into one (since there are only 3 tables) with proper indexes and constraints and then you can check them separately.

2021-03-18 09:39 UTC, shreyanshss7 commented on fyle_slack_app/migrations/0002_reportpollingdetail.py
> +                ('updated_at', models.DateTimeField(auto_now=True)),
Yeah `not null` not need. I'll add it anyway just to be safe.

2021-03-18 11:30 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +    @method_decorator(csrf_exempt)
Removed the middleware and tested stuff, things seem to be working fine.

2021-03-18 11:33 UTC, shreyanshss7 commented on fyle_slack_service/settings.py
> -    'django.middleware.csrf.CsrfViewMiddleware',
Removed CSRF middleware and tested, things seem to be working fine.
Nothing broke in request response flow.

2021-03-18 16:59 UTC, abhishek1234321 approved these changes

2021-03-18 16:59 UTC, abhishek1234321 commented on fyle_slack_app/fyle/authorization/views.py
> +from .. import utils as fyle_utils
so they have a top-level folder called `core` no? could we not do something like that?

2021-03-19 11:13 UTC, closed without merging