Report approve
fylein/fyle-slack-app pull request #20
Opened 2021-03-17 15:08 UTC by shreyanshss7

2021-03-22 10:27 UTC, abhishek1234321 requested changes

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        report_approved_states = ['PAYMENT_PENDING', 'APPROVED', 'PAYMENT_PROCESSING', 'PAID']
let us put `APPROVED` before `PAYMENT_PENDING` because that is how the states change

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +            report_state_message = 'This expense report can\'t be approved as it is sent back to the employee :x:'
shouldn't we be returning here?

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        is_report_approved = False
why do you need both `is_report_approved` and `is_report_approvable`? they will always be opposites no? which means you could just use any one?

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +                        report_state_message = 'This expense report is already approved by you :white_check_mark:'
shouldn't you be breaking the loop here?

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +                        report_state_message = 'Your approval is disabled on this expense report :x:'
need better content, it basically means the user is either disabled from Fyle, or he was removed as an approver for this report and cannot approver anymore

2021-03-22 10:27 UTC, abhishek1234321 commented on fyle_slack_app/slack/ui/report_approvals/messages.py
> +def get_report_approval_notification_message(report, employee_display_name, report_url, message=None):
`get_report_approval_notification`

2021-03-22 10:31 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +def process_report_approval(report_id, user_id, team_id, message_ts):
`message_ts` means message timestamp, this is used to identify which message we want to update.
Will rename `message_ts` -> `message_timestamp` for better user understanding.

2021-03-22 10:31 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +    assertions.assert_found(slack_team, 'Slack team not registered')
No this is not thrown in the UI.

2021-03-22 10:33 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +    approver_report = FyleReportApproval.get_approver_reports(user, query_params)['data'][0]
Yes I considered this case. I was trying to check in webapp if any report can be deleted after it is submitted, I didn't see any option to delete.

2021-03-22 10:34 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        connection = fyle_utils.get_fyle_sdk_connection(user.fyle_refresh_token)
Since refresh token is different for every user we need to do this for every single method.

2021-03-22 10:38 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        'order': 'submitted_at.desc'
This method is usage is temporary for for.
I'll be using the method mentioned in line 104
`# approver_report = FyleReportApproval.get_approver_report_by_id(user, report_id)['data']`
which fetches the report by id only.
I've already asked Adi sir to make the `/approver/reports/{id}` available and it will be done soon.

2021-03-22 10:41 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +        report_state_message = 'Expense report approved by you :white_check_mark:'
Will raise a request for report approval content 👍🏽

2021-03-22 10:49 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        is_report_approved = False
Yes I agree. 
My reason for using two variables was the they both explicitly tell what can be done with the report.
Incase of using one variable, if report is already approved and report cannot be approved won't be distinguished by one variable in terms of reading the code as well.

2021-03-22 10:53 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +                        report_state_message = 'Your approval is disabled on this expense report :x:'
Will raise a request for all report related content in #product_content

2021-03-22 10:57 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        is_report_approved = False
Yes I agree. 
My reason for using two variables was the they both explicitly tell what can be done with the report.
Incase of using one variable, if report is already approved and report cannot be approved won't be distinguished by one variable in terms of reading the code as well.

I'll use one variable check for now.

2021-03-22 11:08 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +            report_state_message = 'This expense report can\'t be approved as it is sent back to the employee :x:'
Using single return statement only, return statements in between looks odd with logic, will use `else if` for better readability here.

2021-03-22 15:25 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +    # Check if report is deleted
Temporary check for the sdk list report method we’re using to fetch a single report.
 Will change the condition when I get proper sdk method.

2021-03-22 17:59 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +
FYI: Have raised content request for all the report related messages in #product_content

2021-03-23 08:59 UTC, abhishek1234321 approved these changes

2021-03-23 08:59 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        connection = fyle_utils.get_fyle_sdk_connection(user.fyle_refresh_token)
can this not be done once in this file, instead of doing it in every method ?

2021-03-23 09:10 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/views.py
> +        connection = fyle_utils.get_fyle_sdk_connection(user.fyle_refresh_token)
Will try to find a more cleaner way. Adding this as a separate task since this thing will cater to whole codebase where fyle sdk is required.

2021-03-23 09:27 UTC, closed without merging