Complete report approve impl
fylein/fyle-slack-app pull request #26
Opened 2021-03-30 12:25 UTC by shreyanshss7

2021-03-30 12:29 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +
- Since we're using background task to process report approval, sending a message in notification message thread to let the user know that their report approve action is being processed.
- Background task because we want to tackle the slack 3 sec timeout issue.
- Please let me know if this is okay or not.
- Also, please spare me for content 🙂

2021-03-31 18:10 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +
Wait, actually this message might not be required
- since all the testing was done on local so api calls from local to a cluster might take a bit more time.
- Once this is deployed on a cluster all the processing should happen quickly.
- Will take a call on this once tested with a deployed version.

2021-04-02 04:56 UTC, abhishek1234321 requested changes

2021-04-02 04:56 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                report = report['data']
is this needed? it isn't used as such

2021-04-02 04:56 UTC, abhishek1234321 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                    'Please try approving again or `View in Fyle` to approve directly from Fyle :zap:'
are we using `View in Fyle` or `Review in Fyle` as the CTA? please be consistent?

2021-04-02 05:29 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                report = report['data']
It is under try except, so if try block runs successfully the code block after except will use this, i.e. line 151.

2021-04-02 05:29 UTC, shreyanshss7 commented on fyle_slack_app/fyle/report_approvals/tasks.py
> +                    'Please try approving again or `View in Fyle` to approve directly from Fyle :zap:'
Ahh yes it should be `Review in Fyle` when `approve` cta is still there.

2021-04-02 12:17 UTC, abhishek1234321 approved these changes

2021-04-28 05:46 UTC, closed without merging