Added test case for report polling
fylein/fyle-slack-app pull request #27
Opened 2021-03-31 10:54 UTC by shreyanshss7

2021-04-02 05:10 UTC, abhishek1234321 requested changes

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +        'currency': 'INR',
test with USD instead?

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +        'is_manually_flagged': True,
manual flag happens only when an approver or admin flags it during report approval, so why test for this?

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +        'reimbursed_at': '2020-06-11T13:14:55.201598+00:00',
this will not be set at approval stage no?

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +        'approved_at': '2020-06-11T13:14:55.201598+00:00',
are you testing report approval?

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +        'source': 'string',
shouldn't mock data have some resemblance to actual stuff?

2021-04-02 05:10 UTC, abhishek1234321 commented on tests/test_report_approval.py
> +    mock_report_details = {
shouldn't we have a certain folder only for writing these mock objects? what does django or the community recommend?

2021-04-02 05:31 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +import mock
It a convention of pytest, it recognises test files and test functions to run only if there is a prefix `test_<name>` in files and test functions

2021-04-02 05:32 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +    mock_report_details = {
Yes we should, there aren't much use case of reports data so kept it here only.

2021-04-02 05:33 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +        'currency': 'INR',
Currency doesn't matter no sir this is just mock test to test the polling function.

2021-04-02 05:34 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +        'is_manually_flagged': True,
Test is not for this sir this is just a mock api response, it doesn't matter if it is false or true.

2021-04-02 05:34 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +        'approved_at': '2020-06-11T13:14:55.201598+00:00',
This test is for report polling sir, approval test case PR will be separate

2021-04-02 05:35 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +        'reimbursed_at': '2020-06-11T13:14:55.201598+00:00',
mock data sir, doesn't matter in polling test case.

2021-05-10 10:41 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +    report_approval_messages.get_report_approval_notification.assert_called_with(mock_report_details, mock_user_display_name, mock_report_url)
Apologies forgot about this PR and test cases 🙁

2021-05-10 10:42 UTC, shreyanshss7 commented on tests/test_report_approval.py
> +
Apologies forgot about this PR and test cases 🙁

2021-05-10 11:16 UTC, shreyanshss7 commented on tests/conftest.py
> +import json
Apologies forgot about this PR and test cases 🙁

2021-05-10 13:34 UTC, shreyanshss7 commented on tests/conftest.py
> +    fyle.approver.reports.list.return_value = mock_data['approver']['reports']['list']
This convention is inline with our platform sdk `fyle.approver.reports.list.return_value`, meaning this is the methods and attributes we call to fetch data

2021-05-10 14:39 UTC, shreyanshss7 commented on tests/conftest.py
> +import json
Update:- Added test cases for both report polling and report approve.

2021-05-20 10:46 UTC, closed without merging