Expense form block suggestions ( form drop down values )
fylein/fyle-slack-app pull request #41
Opened 2021-10-22 04:00 UTC by shreyanshss7

2021-11-01 17:14 UTC, abhishek1234321 requested changes

2021-11-01 17:14 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +            text='Looks like something went wrong :zipper_mouth_face: \n Please try again'
could we raise a Sentry exception failure?

2021-11-01 17:14 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +            'limit': '30',
is it a max limit? if not should we use max limit?

2021-11-01 17:14 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +                project_display_name = project['display_name']
qq: `display_name` can we not use this? why do we need to use this `project_display_name`?

2021-11-01 17:14 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +            'order': 'state.asc',
why do this? could you check what happens in the webapp?

2021-11-02 04:48 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +            'limit': '30',
I think we decided to show only limited ones because of 3 sec timeout and let user enter some text for more values , since we cannot use background tasks in dynamic drop down

2021-11-08 08:01 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_suggestion_handlers.py
> +            'order': 'state.asc',
In web app these are ordered by created at, will change this.

2021-11-08 16:22 UTC, abhishek1234321 approved these changes

2022-05-10 14:20 UTC, closed without merging