Expense form dialog open changes
fylein/fyle-slack-app pull request #42
Opened 2021-10-22 04:10 UTC by shreyanshss7

2021-11-01 16:55 UTC, abhishek1234321 requested changes

2021-11-01 16:55 UTC, abhishek1234321 commented on fyle_slack_app/fyle/expenses/views.py
> +        mandatory_fields_mapping = {
why check for only these fields for mandatory?

2021-11-01 16:55 UTC, abhishek1234321 commented on fyle_slack_app/fyle/expenses/views.py
> +        additional_currency_details = {
currency and amount should also be mandatory

2021-11-01 16:55 UTC, abhishek1234321 commented on fyle_slack_app/fyle/expenses/views.py
> +        add_to_report = 'existing_report'
we should default to existing only if we have reports to add to no?

2021-11-01 16:55 UTC, abhishek1234321 commented on fyle_slack_app/fyle/expenses/views.py
> +            if 'custom_field' in block['block_id'] or 'additional_field' in block['block_id']:
how does this help?

2021-11-01 16:55 UTC, abhishek1234321 commented on fyle_slack_app/fyle/expenses/views.py
> +            custom_field_blocks = None
are we showing all custom fields by default? or only after selection of category?

2021-11-02 04:30 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +            'limit': '20',
hard limit is 100 I guess on platform side, but limit is a mandatory query param

2021-11-02 04:32 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +            'column_name': 'not_in.(purpose, txn_dt, vendor_id, cost_center_id)',
There are additional fields as well for taxi category which have `is_custom` as `false`

2021-11-02 04:33 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +        custom_fields_query_params = {
Custom we'll only get when their category is selected, is there any other case I missed where we fetch custom fields?

2021-11-02 04:35 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +        add_to_report = 'existing_report'
That check will happen where the UI is rendered.

2021-11-02 04:35 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +            custom_field_blocks = None
only after selection of category

2021-11-02 04:37 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +            if 'custom_field' in block['block_id'] or 'additional_field' in block['block_id']:
This helps in dynamic re-rendering of the form, we use the UI's present in slack payload and get the custom fields directly with the key `custom_field` so we don't have to make an API call again while dynamic re-rendering the form

2021-11-03 10:50 UTC, abhishek1234321 requested changes

2021-11-08 07:43 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +            'category_ids': 'cs.[{}]'.format(int(category_id))
Yes will implement this once caching PR is merged.

2021-11-08 07:43 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +    def get_categories(self, query_params: Dict) -> Dict:
Will create a separate PR for this

2021-11-08 16:19 UTC, abhishek1234321 approved these changes

2022-05-10 14:20 UTC, closed without merging