Added expense form action changes
fylein/fyle-slack-app pull request #43
Opened 2021-10-22 04:16 UTC by shreyanshss7

2021-11-01 17:22 UTC, abhishek1234321 requested changes

2021-11-01 17:22 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +            'block_id': 'project_loading_block',
+1

2021-11-01 17:22 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +    def handle_currency_select(self, slack_payload: Dict, user_id: str, team_id: str) -> JsonResponse:
`handle_currency_selection`

2021-11-01 17:22 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +        report_id = 'rpKJGi7nRzMF'
what is this about?

2021-11-02 04:51 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +        report_id = 'rpKJGi7nRzMF'
This was just to complete the flow since report submit api was not available, I used existing report to complete the flow.

2021-11-03 10:59 UTC, abhishek1234321 approved these changes

2021-11-03 10:59 UTC, abhishek1234321 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +        report_id = 'rpKJGi7nRzMF'
add a TODO to clean this up

2022-05-10 14:20 UTC, closed without merging