Django DB caching with decorator
fylein/fyle-slack-app pull request #46
Opened 2021-10-26 11:26 UTC by shreyanshss7

2021-11-08 16:17 UTC, abhishek1234321 requested changes

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this(timeout=60)
should we consider using `KEY_PREFIX`?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this(timeout=60)
should we consider max items in the cache too? so to not bloat the table?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this(timeout=60)
isn't refresh token valid till the user hits a 401 or some 1 year? also, we need to invalidate this when logout, disconnection happens or we hit a 401

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this()
let us keep 1 hour?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this()
also, this method should be cached for the org and not the user, is it possible? basically we define what to be cached in what manner?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this(timeout=60)
is this cached for the user or the entire Slack app? could we verify this?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_service/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
This is an interesting read https://stackoverflow.com/questions/913067/sqlite-as-a-production-database-for-a-low-traffic-site

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_service/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
could we check what is the max concurrent requests we get and check if this can handle 10X of that?

2021-11-08 16:17 UTC, abhishek1234321 commented on fyle_slack_service/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
https://stackoverflow.com/a/6919386/2458378

2021-11-09 06:48 UTC, shreyanshss7 commented on fyle_slack_app/fyle/utils.py
> +@utils.cache_this(timeout=60)
>could we put a default timeout at the config level and override it as and when needed?
- Yes we can have a config level timeout, I think if we keep the timeout parameter mandatory we'll enforce the dev to think about the caching timeout and if the dev misses the timeout parameter it may/may not cause a problem with default timeout for certain functions.

2022-04-04 11:24 UTC, closed without merging