Fetch org_user_ids of slack users, in order to get their org_ids
fylein/fyle-slack-app pull request #59
Opened 2022-01-12 10:48 UTC by jatzz10

2022-01-18 05:39 UTC, shreyanshss7 requested changes

2022-01-18 05:39 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +    query = 'select fyle_user_id, fyle_refresh_token from users;'
can you setup django here like it is in `create_subscription_for_current_users.py` script so that we're making things inside a django environment and don't use raw queries.

2022-01-18 05:39 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +def get_fyle_access_token(fyle_refresh_token: str) -> str:
we already have functions for this right? can we not use them here?

2022-01-18 05:39 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +def get_cluster_domain(fyle_refresh_token: str) -> str:
same as above

2022-01-18 05:39 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +def get_fyle_sdk_connection(refresh_token):
same as above

2022-01-18 05:39 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +def get_fyle_profile(refresh_token):
same as above

2022-01-18 09:16 UTC, jatzz10 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +    query = 'select fyle_user_id, fyle_refresh_token from users;'
Done

2022-01-18 09:16 UTC, jatzz10 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +def get_fyle_access_token(fyle_refresh_token: str) -> str:
done

2022-01-18 09:23 UTC, shreyanshss7 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +    slack_users = get_slack_users_data()
Why is the function call needed? Asking since the only working 1 line in the function is to get the data.

2022-01-18 09:28 UTC, shreyanshss7 approved these changes

2022-01-18 09:34 UTC, jatzz10 commented on scripts/fetch_org_id_for_existing_slack_users.py
> +    slack_users = get_slack_users_data()
just for better readability
don't have any strong reason

2022-01-20 05:48 UTC, gokulk16 approved these changes

2022-01-25 11:47 UTC, merged