[Release 2] Visa changes - "Attach flow"
fylein/fyle-slack-app pull request #78
Opened 2022-04-18 12:46 UTC by jatzz10

2022-04-28 06:21 UTC, shreyanshss7 commented on fyle_slack_app/slack/interactives/block_action_handlers.py
> +        if len(expense['data'][0]['files']) > 0:
This might break for normal expenses attach flow when the expense is deleted.

2022-04-28 06:27 UTC, shreyanshss7 commented on fyle_slack_app/slack/events/tasks.py
> +                receipt_uploading_message_block = common_messages.get_custom_text_section_block(receipt_uploading_message)
we can directly use `text` parameter in `slack_client.chat_postMessage` instead of creating a block for a single line text message.

2022-04-28 09:50 UTC, shreyanshss7 commented on fyle_slack_app/slack/ui/notifications/messages.py
> +    attach_receipt_section = get_card_expense_attach_receipt_action('Attach Receipt', expense['id'])
If the func says `attach_receipt` action then why pass `Attach Receipt` text as a parameter?

2022-04-28 09:50 UTC, shreyanshss7 commented on fyle_slack_app/slack/events/tasks.py
> +    with transaction.atomic():
with `with transaction.atomic():` is not helpful here, I've removed it from my end as well. Please to remove it from here.

2022-04-28 09:52 UTC, shreyanshss7 commented on fyle_slack_app/fyle/expenses/views.py
> +        return self.connection.v1beta.spender.expenses.list(query_params=query_params)
Since this is a list expenses call, we should check if the matching expense is returned or not and if not we should return None.

2022-04-29 06:54 UTC, jatzz10 commented on fyle_slack_app/slack/events/tasks.py
> +                receipt_uploading_message_block = common_messages.get_custom_text_section_block(receipt_uploading_message)
Correct, but I noticed that we update the message with `text` parameter, in the slack this small message `(edited)` shows up after the message.
So, to avoid that, using `block` parameter -> have tested this out

2022-04-29 06:56 UTC, jatzz10 commented on fyle_slack_app/fyle/expenses/views.py
> +        return self.connection.v1beta.spender.expenses.list(query_params=query_params)
not following; let's please discuss this on call

2022-04-29 07:35 UTC, shreyanshss7 commented on fyle_slack_app/fyle/utils.py
> +        return False, response_message
use `is_receipt_supported` to keep track of `False` and `True` values and use only one return statement at the end instead of 3-4

2022-04-29 07:49 UTC, shreyanshss7 commented on fyle_slack_app/slack/events/tasks.py
> +        is_file_supported, file_response_message = fyle_utils.is_receipt_file_supported(file_info)
This check should be done after line `144` since we only want to run these checks on threads of expenses only. Otherwise this check would run when we add a file to any other notification.

2022-05-03 11:26 UTC, jatzz10 commented on fyle_slack_app/fyle/expenses/views.py
> +        return self.connection.v1beta.spender.expenses.list(query_params=query_params)
```
response = self.connection.v1beta.spender.expenses.list(query_params=query_params)
expense = response['data'] if response['count'] == 1 else None
```

2022-05-03 11:27 UTC, jatzz10 commented on fyle_slack_app/fyle/utils.py
> +def is_receipt_file_supported(file_info: Dict):
`def is_receipt_file_supported(file_info: Dict) -> Union[bool, str]:`

2022-05-03 11:35 UTC, jatzz10 commented on fyle_slack_app/slack/events/tasks.py
> +            'task': expense_id,
expense_id

2022-05-03 11:51 UTC, shreyanshss7 approved these changes

2022-05-04 12:11 UTC, gokulk16 requested changes

2022-05-04 12:11 UTC, gokulk16 commented on fyle_slack_app/slack/events/tasks.py
> +        parent_message_blocks[1]['fields'][1]['text'] = 'Receipt:\n :white_check_mark: *Attached*'
identify the field more concretely

2022-05-04 12:11 UTC, gokulk16 commented on fyle_slack_app/slack/events/tasks.py
> +        if len(parent_message_blocks[3]['elements']) > 1:
identify concretely than going by the expected results

2022-05-04 12:11 UTC, gokulk16 commented on fyle_slack_app/slack/events/tasks.py
> +    if attached_receipt is not None:
- file_attached_respond_in_thread()
- file_Attached_update_parent_message()

2022-05-06 06:51 UTC, jatzz10 commented on fyle_slack_app/slack/events/tasks.py
> +        if len(parent_message_blocks[3]['elements']) > 1:
Have left this for now
I am planning to do this in a separate PR

2022-05-06 06:52 UTC, jatzz10 commented on fyle_slack_app/slack/events/tasks.py
> +                        receipt_uploading_message = ':mag: Uploading receipt.... Your receipt will be attached shortly!'
confirmed

2022-05-06 06:52 UTC, jatzz10 commented on fyle_slack_app/slack/events/tasks.py
> +        parent_message_blocks[1]['fields'][1]['text'] = 'Receipt:\n :white_check_mark: *Attached*'
Have left this for now
I am planning to do this in a separate PR

2022-05-06 08:03 UTC, shreyanshss7 commented on fyle_slack_app/slack/utils.py
> +    slack_client.chat_update(
why is this a function? Please remove this and do this at the caller side only. It's not helping to having a function to update the message only.

2022-05-06 09:35 UTC, gokulk16 approved these changes

2022-05-06 09:35 UTC, gokulk16 commented on fyle_slack_app/slack/events/handlers.py
> +
remove

2022-05-06 09:35 UTC, gokulk16 commented on fyle_slack_app/slack/events/tasks.py
> +    if 'thread_ts' in file_message_details:
use assert methods.

2022-05-06 09:35 UTC, gokulk16 commented on fyle_slack_app/slack/events/tasks.py
> +    if 'thread_ts' in file_message_details:
def functionA:
    assertions
    known failure cases
    success case
    unknown failure cases

2022-05-06 09:45 UTC, jatzz10 commented on fyle_slack_app/slack/utils.py
> +    slack_client.chat_update(
removed it

2022-05-06 09:52 UTC, merged