Made Amount Fraction Currency Specific
fylein/fyle-slack-app pull request #88
Opened 2022-09-22 05:50 UTC by OmkarJ13

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19TNHMHQeDXq1bgCDLKS1NeRPJpL1q8LuY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vn55oE8)

2022-09-22 08:57 UTC, OmkarJ13 commented on fyle_slack_app/slack/events/handlers.py
> -            total_amount = round(sum(report['amount'] for report in sent_back_reports), 2)
Rounding is not needed here, we will round off when displaying the `total_amount`

2022-09-22 08:57 UTC, OmkarJ13 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(filter(None, (expense['amount'] for expense in incomplete_expenses)))
Fixed [this](https://fylein.slack.com/archives/CLL8281FD/p1663825974391349) issue.

2022-09-22 08:57 UTC, OmkarJ13 commented on fyle_slack_app/slack/interactives/tasks.py
> +            amount = float(amount)
Rounding is not needed here as this is foreign amount, we will round off the calculated final amount

2022-09-22 08:57 UTC, OmkarJ13 commented on fyle_slack_app/slack/ui/modals/messages.py
> -    report_currency_symbol = slack_utils.get_currency_symbol(report['currency'])
Dont need to get currency symbol separately, all will be contained inside `display_amount` only

2022-09-22 08:57 UTC, OmkarJ13 commented on fyle_slack_app/slack/utils.py
> -def get_currency_symbol(currency: str) -> str:
This function is not needed anymore, we can get currency symbols from the `Babel` library only

2022-09-22 08:57 UTC, OmkarJ13 commented on requirements.txt
> -forex-python==1.8
This library not needed, confirmed that we're not using it anywhere else.

2022-09-23 07:14 UTC, abhishek1234321 approved these changes

2022-09-27 06:48 UTC, jatzz10 requested changes
@OmkarJ13 added few minor comments
please fix or reply back
please to test these changes for - 
- spender notifications
- admin notifications
- add/edit expense
- task dashboard under HOME tab in slack app

2022-09-27 06:48 UTC, jatzz10 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(filter(None, (expense['amount'] for expense in incomplete_expenses)))
@OmkarJ13 please add this same fix in other places as well, in line no. - `150, 162, 203`

2022-09-27 06:48 UTC, jatzz10 commented on fyle_slack_app/slack/ui/notifications/messages.py
> +                        slack_utils.get_display_amount(report['amount'], report['currency'])
please use a variable here
initialise this in line 10

2022-09-27 06:48 UTC, jatzz10 commented on fyle_slack_app/slack/utils.py
> +    currency_has_symbol = currency != currency_symbol
let's rename this to `is_currency_having_symbol`

2022-09-27 06:48 UTC, jatzz10 commented on fyle_slack_app/slack/utils.py
> +    # If the currency doesnt have any symbol, the currency code is returned
`doesn't` 😛

2022-09-27 06:48 UTC, jatzz10 commented on fyle_slack_app/slack/utils.py
> +    format_string = '{:,.' + str(currency_precision) + 'f}'
@OmkarJ13 
1. don't understand why this is required?
2. why is line 147 and 151 required?
3. instead of line 151, can't we use `round_amount` function?

2022-09-27 08:13 UTC, OmkarJ13 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(filter(None, (expense['amount'] for expense in incomplete_expenses)))
@jatzz10 I think it might not be needed there, since there we are checking the `draft reports` `sent back reports` and `unreported expenses`. 
There won't be any case (unless it is bad data) where will get `None` for amount in those scenarios.
Verified this on `prod-us`
<img width="594" alt="image" src="https://user-images.githubusercontent.com/65808188/192470464-72b9230d-521a-4cbd-9006-63b445e9c2ac.png">

2022-09-27 08:41 UTC, OmkarJ13 commented on fyle_slack_app/slack/utils.py
> +    format_string = '{:,.' + str(currency_precision) + 'f}'
This is needed and we can't use the `round_amount` function here because
- The `round_amount` function returns a `float`, as it internally just uses the built in python `round()` function and gets the number to which we should round off the amount from `Babel`
- In the create/edit expense modal, we are using this `round_amount` to basically round off the home currency amount after either the foreign currency amount or exchange rate has been changed.
- Here, we need an amount for representational purposes, with comma separators and all other fancy stuff.
  - So, what `round` returns is not what we want
    - `round(10564.4, 2) -> 10564.4`
  - What we want can be achieved with a python format string
    - `'{:,2f}'.format(10564.4) -> '10,564.40'`

2022-09-27 08:45 UTC, OmkarJ13 commented on fyle_slack_app/slack/ui/notifications/messages.py
> +                        slack_utils.get_display_amount(report['amount'], report['currency'])
Done ✅

2022-09-27 08:45 UTC, OmkarJ13 commented on fyle_slack_app/slack/utils.py
> +    currency_has_symbol = currency != currency_symbol
Done ✅

2022-09-27 08:45 UTC, OmkarJ13 commented on fyle_slack_app/slack/utils.py
> +    # If the currency doesnt have any symbol, the currency code is returned
😂 
Done ✅

2022-09-30 06:10 UTC, jatzz10 approved these changes
lgtm

2022-10-06 06:13 UTC, gokulk16 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(report['amount'] for report in draft_reports)
are we not rounding here?

2022-10-06 06:13 UTC, gokulk16 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(report['amount'] for report in sent_back_reports)
are we not rounding the amount using the currency?

2022-10-06 06:40 UTC, OmkarJ13 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(report['amount'] for report in sent_back_reports)
Nope, we did not round here because the rounding is done in [this](https://github.com/fylein/fyle-slack-app/pull/88/files/b7e835e1245c63e538ec8471f6d6a9ebe6bd9e5d#diff-9150a00fd47620de834a824530c2151baffbbd8e8bb5dff2b97bc054166b9d72) file. Don't need to round here.

2022-10-06 06:41 UTC, OmkarJ13 commented on fyle_slack_app/slack/events/handlers.py
> +            total_amount = sum(report['amount'] for report in draft_reports)
same reason as above

2022-10-06 14:09 UTC, gokulk16 approved these changes

2022-10-07 13:17 UTC, merged